import GithubSlugger from "github-slugger";
import { toString } from "mdast-util-to-string";
import remarkParse from "remark-parse";
import { unified } from "unified";
import { visit } from "unist-util-visit";

export interface TOCItem {
	id: string;
	title: string;
	depth: number;
}

/**
 * Parses markdown content and extracts headings for Table of Contents
 * Uses github-slugger to match ids generated by rehype-slug
 */
export async function extractTOC(content: string): Promise<TOCItem[]> {
	const slugger = new GithubSlugger();
	const processor = unified().use(remarkParse);
	const tree = processor.parse(content);

	const toc: TOCItem[] = [];

	visit(tree, "heading", (node: any) => {
		const text = toString(node);
		// skip empty headings
		if (!text)
			return;

		const id = slugger.slug(text);

		toc.push({
			id,
			title: text,
			depth: node.depth,
		});
	});

	return toc;
}
