export enum RouteName {
  Dashboard = "dashboard",
  Post = "post",
  ViewPost = "view-posts",
  EditPost = "edit-posts",
  EditCategory = "edit-category",
  Note = "note",
  ViewNote = "view-notes",
  EditNote = "edit-notes",
  Topic = "topic",
  Comment = "comment",
  Page = "page",

  ListPage = "page-list",
  EditPage = "page-edit",
  ListSay = "say-list",
  Friend = "friends",
  File = "files",
  Analyze = "analyze",
  Setting = "setting",
  Profile = "setting-profile",
  System = "setting-system",
  Security = "setting-security",
  Reset = "reset",
  Login = "login",
  Home = "home",
  ListShortHand = "shorthand",

  Ai = "ai",
  AiSummary = "ai-summary",
  AiTranslation = "ai-translation",
  AiTranslationEntries = "ai-translation-entries",
  AiTimeCapsule = "ai-time-capsule",

  Reader = "reader",
  Draft = "draft",
  Meilisearch = "meilisearch",
}
